### ISSUE TITLE
Error when requiring module: fs.readFileSync is not a function

### ISSUE THREAD

**Issue by jhubert** [theoephraim/node-google-spreadsheet#32] opened 2015-04-22 16:52 UTC
I'm getting the following error when requiring the module in my project:

![image](https://cloud.githubusercontent.com/assets/3384/7280056/35fff0d0-e8d5-11e4-81b5-cbb36bc027bf.png)

Would this have anything to do with me trying to run it in the browser? Does this package need to be run in node to work?

**Comment by theoephraim** [comment] 2015-04-22 17:47
yes, this is designed to be run in node.

Not sure how you would go about connecting to your database or reading the migration files from the browser...

**Comment by theoephraim** [comment] 2015-04-27 05:53
I'm guessing the issue is xml2js, but I'm not really sure why anything would need the `fs` module.

How are you trying to include this in your project? If you give me a sample project, I may be able to get it working.

**Comment by theoephraim** [comment] 2020-02-03 18:50
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄

**Closed by theoephraim** 2020-02-03 18:50 UTC
