### ISSUE TITLE
setValue giving Error: options.uri is a required argument

### ISSUE THREAD

**Issue by chamoda** [theoephraim/node-google-spreadsheet#90] opened 2016-03-07 08:51 UTC
I don't if if I did anything wrong but I can't set a value

``` javascript
cell.setValue("test", function(err) {
      console.log(err);
});
```

I'm getting `options.uri is a required argument`

let me know if there is another way to save things. I tried save() but did't work

**Comment by theoephraim** [comment] 2016-03-17 01:48
Just released a big update! Please upgrade to the latest version and let me know if you are still having problems. Thanks :)

**Comment by servermeta** [comment] 2016-03-28 17:32
still a problem @ 2.0.1 and @ 1.4.1

**Comment by servermeta** [comment] 2016-05-15 19:14
`
async function promisedUpdateSheet (sheetId, values, workSheetId = 1) {

    let workSheet = await promisedWorkSheet(sheetId, workSheetId);

    let cells = await promisedCells(workSheet);



    values.forEach(function (value){
        cells.forEach( function (cell, index) {
            if (value.col === cell.col && value.row === cell.row) {
                cell.value=value.value;
                cell.save(function(err){
                    if (err) {
                    console.log(err); }
                });
                console.log('matched' + cells[index].value);
                return;
            }
        });

    });


}
`

returns:

`
[Error: options.uri is a required argument]
`

Still a problem with recent version.

**Comment by servermeta** [comment] 2016-05-16 08:16
I had a thought: I'm using Meteor.Js, which uses an old version of node. Maybe this is the problem? The strange thing is that it stopped working a few months ago, before it was fine.

**Comment by gtorodelvalle** [comment] 2016-11-06 12:07
Hi guys! It does not seem to be an issue related to the Node version since I just confirmed that it do happens to me using v0.10.46, v0.12.16, v4.6.0 and v6.7.0 :)

In my case, I am getting this `options.uri` missing error when executing a `SpreadsheetWorksheet.clear()` which internally uses the `SpreadsheetCell.setValue()` as far as I saw: https://github.com/theoephraim/node-google-spreadsheet/blob/master/index.js#L397

Any help on this is more than appreciated! ;)

Thanks!

**Comment by gtorodelvalle** [comment] 2016-11-06 12:10
As mentioned by @josmcg in this issue, it is related to the use of the `request` package: https://github.com/request/request/issues/1509

**Comment by servermeta** [comment] 2016-11-06 12:47
@gtorodelvalle  I solved this by writing my own library, using promises and the API v4. It radically solves the problem by delegating the request to the new API library. If you want I can send you the code.

**Comment by gtorodelvalle** [comment] 2016-11-23 13:08
@servermeta , any plans tu publish it as an NPM package? :)

**Comment by gregorskii** [comment] 2016-11-23 20:45
@servermeta yes do you plan to share? :)

**Comment by theoephraim** [comment] 2020-02-03 18:46
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄

**Closed by theoephraim** 2020-02-03 18:46 UTC
